module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      "cars",
      [
        {
          car_id: 1,
          owner_email: "eyal@gmail.com",
          brand: "Reno",
          year: 2009,
          model: "Megan",
          fuel: "95",
          price_per_day: 30,
          price_per_week: 20,
          price_per_month: 10,
          is_rented: false,

          passengers: 5,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 2,
          owner_email: "jino@gmail.com",
          brand: "Suzuki",
          year: 2014,
          fuel: "95",
          model: "Alto",
          price_per_day: 25,
          price_per_week: 20,
          price_per_month: 15,
          is_rented: false,
          passengers: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 3,
          owner_email: "eliav@gmail.com",
          brand: "toyota",
          year: 2018,
          fuel: "95",
          model: "CHR",
          price_per_day: 30,
          price_per_week: 25,
          price_per_month: 20,
          is_rented: true,
          passengers: 5,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 4,
          owner_email: "lea.shosh@walla.co.il",
          brand: "ford",
          year: 2016,
          fuel: "95",
          model: "focus",
          price_per_day: 10,
          price_per_week: 70,
          price_per_month: 60,
          is_rented: false,
          passengers: 5,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 5,
          owner_email: "oded.mar@hotmail.com",
          brand: "Skoda",
          year: 1989,
          fuel: "Soler",
          model: "Superb",
          price_per_day: 10,
          price_per_week: 7,
          price_per_month: 5,
          is_rented: true,
          passengers: 5,
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("cars", null, {});
  },
};
