///////////////auth
 {
          user_email: "Efi@gmail.com",
          full_name: "Efi Tirsh",
          password: "0542732556",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_email: "Eitan.ach@gmail.com",
          full_name: "Eitan Ach",
          password: "0505732998",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_email: "Pittie@gmail.com",
          full_name: "Pittie Leshem",
          password: "0525732117",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_email: "lior.amz@walla.co.il",
          full_name: "Lior Amzalleg",
          password: "0545985666",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_email: "Meshi.B@hotmail.com",
          full_name: "Meshi Barouch",
          password: "0589678778",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_email: "Sonia@gmail.com",
          full_name: "Sonia Fish",
          password: "0588623778",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_email: "Eyal.Shani@gmail.com",
          full_name: "Eyal Shani",
          password: "0589623678",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_email: "Elizour@hotmail.com",
          full_name: "Elizour Pour",
          password: "0589623778",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_email: "Moshe@hotmail.com",
          full_name: "Moshe Rabenu",
          password: "0589623778",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_email: "Harry@hotmail.com",
          full_name: "Harry Potter",
          password: "058963778",
          created_at: new Date(),
          updated_at: new Date(),
        },
        ////////////////////////////////cars/////////////
        {
          car_id: 31,
          owner_email: "Efi@gmail.com",
          brand: "PEUGEOT",
          year: 2012,
          model: "505",
          fuel: "OCTAN-95",
          price_per_day: 60,
          discount_for_week: "5%",
          discount_for_month: "10%",
          is_rented: false,
          passengers: 5,
          available_from: new Date(),
          available_until: new Date(
            new Date().setMonth(new Date().getMonth() + 1)
          ),
          gear: "Manual",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 32,
          owner_email: "Eitan.ach@gmail.com",
          brand: "MAZDA",
          year: 2014,
          fuel: "OCTAN-95",
          model: "Mazda3",
          price_per_day: 85,
          discount_for_week: "10%",
          discount_for_month: "15%",
          is_rented: false,
          passengers: 4,
          available_from: new Date(),
          available_until: new Date(
            new Date().setMonth(new Date().getMonth() + 1)
          ),
          gear: "Auto",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 33,
          owner_email: "Pittie@gmail.com",
          brand: "TOYOTA",
          year: 2018,
          fuel: "OCTAN-95",
          model: "COROLLA",
          price_per_day: 75,
          discount_for_week: "10%",
          discount_for_month: "20%",
          is_rented: true,
          passengers: 5,
          available_from: new Date(),
          available_until: new Date(
            new Date().setMonth(new Date().getMonth() + 3)
          ),
          gear: "Manual",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 34,
          owner_email: "lior.amz@walla.co.il",
          brand: "FORD",
          year: 2016,
          fuel: "OCTAN-95",
          model: "Focus",
          price_per_day: 78,
          discount_for_week: "5%",
          discount_for_month: "10%",
          is_rented: false,
          passengers: 5,
          available_from: new Date(),
          available_until: new Date(
            new Date().setMonth(new Date().getMonth() + 2)
          ),
          gear: "Manual",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 35,
          owner_email: "Meshi.B@hotmail.com",
          brand: "PEUGEOT",
          year: 2016,
          fuel: "SOLER",
          model: "405",
          price_per_day: 20,
          discount_for_week: "5%",
          discount_for_month: "10%",
          is_rented: true,
          passengers: 9,
          available_from: new Date(),
          available_until: new Date(
            new Date().setMonth(new Date().getMonth() + 4)
          ),
          gear: "Manual",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 36,
          owner_email: "Sonia@gmail.com",
          brand: "MAZDA",
          year: 2002,
          fuel: "SOLER",
          model: "Mazda3",
          price_per_day: 39,
          discount_for_week: "10%",
          discount_for_month: "25%",
          is_rented: true,
          passengers: 9,
          available_from: new Date(),
          available_until: new Date(
            new Date().setMonth(new Date().getMonth() + 2)
          ),
          gear: "Auto",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 37,
          owner_email: "Eyal.Shani@gmail.com",
          brand: "TESLA",
          year: 2012,
          fuel: "ELECTRIC",
          model: "Model 3",
          price_per_day: 90,
          discount_for_week: "5%",
          discount_for_month: "25%",
          is_rented: true,
          passengers: 5,
          available_from: new Date(),
          available_until: new Date(
            new Date().setMonth(new Date().getMonth() + 12)
          ),
          gear: "Auto",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 38,
          owner_email: "Elizour@hotmail.com",
          brand: "TOYOTA",
          year: 2020,
          fuel: "OCTAN-95",
          model: "YARIS",
          price_per_day: 55,
          discount_for_week: "20%",
          discount_for_month: "25%",
          is_rented: true,
          passengers: 5,
          available_from: new Date(),
          available_until: new Date(
            new Date().setMonth(new Date().getMonth() + 8)
          ),
          gear: "Auto",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 39,
          owner_email: "Moshe@hotmail.com",
          brand: "BMW",
          year: 2018,
          fuel: "Soler",
          model: "X6",
          price_per_day: 110,
          discount_for_week: "5%",
          discount_for_month: "25%",
          is_rented: true,
          passengers: 5,
          available_from: new Date(),
          available_until: new Date(
            new Date().setMonth(new Date().getMonth() + 14)
          ),
          gear: "Manuel",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 40,
          owner_email: "Harry@hotmail.com",
          brand: "FORD",
          year: 2017,
          fuel: "GAS",
          model: "Transit",
          price_per_day: 100,
          discount_for_week: "10%",
          discount_for_month: "15%",
          is_rented: true,
          passengers: 7,
          available_from: new Date(),
          available_until: new Date(
            new Date().setMonth(new Date().getMonth() + 8)
          ),
          gear: "Auto",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 41,
          owner_email: "Pittie@gmail.com",
          brand: "TOYOTA",
          year: 2021,
          fuel: "OCTAN-95",
          model: "PRIUS",
          price_per_day: 75,
          discount_for_week: "0%",
          discount_for_month: "5%",
          is_rented: true,
          passengers: 5,
          available_from: new Date(),
          available_until: new Date(
            new Date().setMonth(new Date().getDay() + 17)
          ),
          gear: "Auto",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 42,
          owner_email: "lior.amz@walla.co.il",
          brand: "MAZDA",
          year: 1989,
          fuel: "SOLER",
          model: "Mazda6",
          price_per_day: 50,
          discount_for_week: "25%",
          discount_for_month: "50%",
          is_rented: true,
          passengers: 5,
          available_from: new Date(),
          available_until: new Date(
            new Date().setMonth(new Date().getMonth() + 6)
          ),
          gear: "Auto",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 43,
          owner_email: "Moshe@hotmail.com",
          brand: "PEUGEOT",
          year: 2013,
          fuel: "OCTAN-95",
          model: "505",
          price_per_day: 110,
          discount_for_week: "0%",
          discount_for_month: "10%",
          is_rented: true,
          passengers: 5,
          available_from: new Date(),
          available_until: new Date(
            new Date().setMonth(new Date().getMonth() + 8)
          ),
          gear: "Manual",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 44,
          owner_email: "Moshe@hotmail.com",
          brand: "BMW",
          year: 2019,
          fuel: "Gas",
          model: "128i",
          price_per_day: 130,
          discount_for_week: "15%",
          discount_for_month: "30%",
          is_rented: true,
          passengers: 2,
          available_from: new Date(),
          available_until: new Date(
            new Date().setMonth(new Date().getMonth() + 4)
          ),
          gear: "Auto",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 45,
          owner_email: "Pittie@gmail.com",
          brand: "TOYOTA",
          year: 2000,
          fuel: "GAS",
          model: "COROLLA",
          price_per_day: 30,
          discount_for_week: "10%",
          discount_for_month: "25%",
          is_rented: true,
          passengers: 5,
          available_from: new Date(),
          available_until: new Date(
            new Date().setMonth(new Date().getMonth() + 9)
          ),
          gear: "Manual",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          car_id: 46,
          owner_email: "Meshi.B@hotmail.com",
          brand: "TESLA",
          year: 2020,
          fuel: "ELECTRIC",
          model: "MODEL X",
          price_per_day: 165,
          discount_for_week: "0%",
          discount_for_month: "5%",
          is_rented: true,
          passengers: 2,
          available_from: new Date(),
          available_until: new Date(
            new Date().setMonth(new Date().getMonth() + 22)
          ),
          gear: "Auto",
          created_at: new Date(),
          updated_at: new Date(),
        },
        ///////////////////////users
                {
          user_email: "Efi@gmail.com",
          first_name: "Efi",
          last_name: "Tirsh",
          phone_number: "0542732556",
          address: "TEL AVIV - YAFO",
          rating: 4,
          number_of_votes: 12,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_email: "Eitan.ach@gmail.com",
          first_name: "Eitan",
          last_name: "Ach",
          phone_number: "0505732998",
          address: "TEL AVIV - YAFO",
          rating: 2.6,
          number_of_votes: 46,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_email: "Pittie@gmail.com",
          first_name: "Pittie",
          last_name: "Leshem",
          phone_number: "0525732117",
          address: "TEL AVIV - YAFO",
          rating: 4,
          number_of_votes: 145,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_email: "lior.amz@walla.co.il",
          first_name: "Lior",
          last_name: "Amzalleg",
          phone_number: "0545985666",
          address: "TEL AVIV - YAFO",
          rating: 0.7,
          number_of_votes: 45,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_email: "Meshi.B@hotmail.com",
          first_name: "Meshi",
          last_name: "Barouch",
          phone_number: "0589678778",
          address: "TEL AVIV - YAFO",
          rating: 5,
          number_of_votes: 10,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_email: "Sonia@gmail.com",
          first_name: "Sonia",
          last_name: "Fish",
          phone_number: "0588623778",
          address: "TEL AVIV - YAFO",
          rating: 2,
          number_of_votes: 10,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_email: "Eyal.Shani@gmail.com",
          first_name: "Eyal",
          last_name: "Shani",
          phone_number: "0589623678",
          address: "TEL AVIV - YAFO",
          rating: 3,
          number_of_votes: 22,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_email: "Elizour@hotmail.com",
          first_name: "Elizour",
          last_name: "Pour",
          phone_number: "0589623778",
          address: "TEL AVIV - YAFO",
          rating: 5,
          number_of_votes: 10,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_email: "Moshe@hotmail.com",
          first_name: "Moshe",
          last_name: "Rabenu",
          phone_number: "0589623778",
          address: "TEL AVIV - YAFO",
          rating: 1,
          number_of_votes: 10,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_email: "Harry@hotmail.com",
          first_name: "Harry",
          last_name: "Potter",
          phone_number: "058963778",
          address: "TEL AVIV - YAFO",
          rating: 5,
          number_of_votes: 50,
          created_at: new Date(),
          updated_at: new Date(),
        },